# Generated by Django 5.2.5 on 2025-08-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='penalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
